apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gurukool-backend-hpa
  namespace: gurukool
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gurukool-backend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gurukool-frontend-hpa
  namespace: gurukool
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gurukool-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
