apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gurukool-ingress
  namespace: gurukool
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.gurukool.app
        - api.gurukool.app
      secretName: gurukool-tls
  rules:
    - host: app.gurukool.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api.gurukool.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
